### ISSUE TITLE
How long does these session live?

### ISSUE THREAD

**Issue by mrniamster** [crypto-su/instagramProfileApiHack#1]
Thanks,crypto-su for solution,

- but is there any way to get these session id from user window?

- How long does these session id are valid?

**Comment by crypto-su** [comment]
1- Log into an Instagram account with Google Chrome.

2- Then open a new tab and visit the link below. https://www.instagram.com/instagram/?__a=1

3- Right click on Chrome and inspect.

4- Select Network.

5- Refresh the page.

6- Select ?__a=1 from the left.

On the right, in Request Headers, you will see the session ID under Cookie.


It is a permanent identity.

**Comment by jonnycbw** [comment]
This stops working as soon as the user is logged out, the cookies get cleared and invalidated by IG
